# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyChatCloudFunction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyChatCloudFunction
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

pod 'MessageKit'
pod 'RealmSwift'
pod 'SDWebImage'
pod 'RNCryptor'

end
